### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by rock-517** [aminzabardast/SIFT-on-MATLAB#2]
undefined variable "cv" or class "cv.FeatureDetector".

Error in training (line 52)
detector = cv.FeatureDetector('ORB');

Error in demo_gui>pushbutton3_Callback (line 94)
training(handles.videoDir, handles.dataDir, opts);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in demo_gui (line 26)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)demo_gui('pushbutton3_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback

**Comment by aminzabardast** [comment]
There is no such code in this repository. This is not a machine learning algorithm sot the word "training" is irrelevant. Also, there is no Graphical User Interface here so anything "gui" is irrelevant.
Explain your issue further.
